### PR TITLE
Add Compatibility for Pydantic v2

### PR DESCRIPTION
**Pull request by japerry911**
## Summary

- makes `prefect-fivetran` compatible with Pydantic v2 Installed.

## Relevant Issue(s)

#16 
#15 

## Checklist
- [x] Summarized PR's changes in [CHANGELOG.md](https://github.com/pubchimps/prefect-fivetran/blob/main/CHANGELOG.md)

### CODE REVIEW

**Review by adboldyrev — APPROVED** [review]
LGTM

**Review by adboldyrev — APPROVED** [review]

**Review by fivetran-nenad-stanojev — APPROVED** [review]

**Comment by japerry911** [comment]
@fivetran-aleksandrboldyrev @fivetran-nenad-stanojev 

Are these tests outdated?

**Comment by adboldyrev** [comment]
> @fivetran-aleksandrboldyrev @fivetran-nenad-stanojev
> 
> Are these tests outdated?

Looks like - yes

**Comment by japerry911** [comment]
closing as another PR addresses this

**Pull request closed without merging**
